### ISSUE TITLE
Some data comes from database and some comes from dataHelperClass

### ISSUE THREAD

**Issue by mrrobrob** [jackapie/My-Wildlife-Garden#1]
This should all be moved into database.

How will you deal with the higher level category you need to have (ie: inverts, mammals, plants)?

**Comment by jackapie** [comment]
I created a SectionModel to deal with the higher level categories.
In DatabaseHelper, I created a lambda expression to specify the section (to match SectionName) in the database the category list should be retrieved from and made necessary adjustments to HomeController.
